"""Regenerate GEMINI-SKILL.md from the rulebook and the run prompt:
python predictbot/chat/build_gemini_skill.py"""
from pathlib import Path

HERE = Path(__file__).resolve().parent


def build() -> str:
    rb = (HERE / "PCBF-MINI-v1.4.md").read_text(encoding="utf-8")
    version = rb.splitlines()[0].replace("# ", "").split(" (")[0]          # e.g. PCBF Mini v1.4.2
    body = rb[rb.index("## Labels"):].replace("Kaye", "the user")
    run = (HERE / "DAILY-RUN-PROMPT.md").read_text(encoding="utf-8")
    head = "OUTPUT (this order, nothing else)"
    out = run[run.index(head) + len(head):run.index('End with: "Recheck')].strip()
    instructions = f"""You run {version}: compare Bet9ja prices with the fair market price and flag the ones where Bet9ja pays more. You never place bets. Start as soon as the user uploads Bet9ja capture files or pastes odds. Process every attached file and every sport. Do not ask whether to continue. Zero PICKs is a valid result; do not stretch to fill a table.

Before anything else, run the Python block below with your code tool and confirm its self-checks pass. Use code for every calculation. If you cannot run code, stop and say so. Use web search for benchmarks and news.

Two sources never mix: numbers come only from code (the Python block on benchmark prices); news comes from search and only adds a note. It never changes a number, a label or the ledger. Pundit and tipster picks are opinion, not benchmarks.

CONFIRMED SETTLEMENT RULES (anything not listed is unconfirmed): none yet. The user may paste an updated list with a run; use the latest one.

{body.strip()}

## Output (this order, nothing else)
{out}

End with: "Recheck every Bet9ja price before placing; skip it if below min odds. No real money without a written evidence review."
"""
    slug = version.lower().replace("pcbf mini ", "pcbf-mini-").replace(".", "-")
    return f"""# {version} as a Gemini skill

Copy each block into the matching field. Generated by build_gemini_skill.py from PCBF-MINI-v1.4.md and DAILY-RUN-PROMPT.md; rerun it after changing either.

## Name

```
{slug}
```

## Description

```
Compares Bet9ja odds with same-day fair prices (Pinnacle, OddsPortal average, Oddschecker, Polymarket) using the {version} rulebook, labels every selection PICK / WATCH / RESEARCH / REJECTED, and returns a ledger CSV. Use when the user uploads Bet9ja capture files (bet9ja-allsports-walk-*.json, bet9ja-soccer-*.json) or pastes Bet9ja odds, or says "run PCBF", "today's picks", "price these fixtures" or "settle".
```

## Instructions

````
{instructions.strip()}
````
"""


if __name__ == "__main__":
    (HERE / "GEMINI-SKILL.md").write_text(build(), encoding="utf-8")
    print("wrote GEMINI-SKILL.md")
